### PR TITLE
Summarize the rates 

### PR DESCRIPTION
**Pull request by kriskoin**
### GH Issue couldn't find it

this feature summarize the rates and store the processed data within the blockchain
 
### Steps to test
**1.** compile adding the full path of the contract using the flag **-I**

_eosio-cpp  eoseosrateio.cpp -o eoseosrateio.wasm  -abigen -**I {CONTRACT_PATH}**_

**2.** feed the stats, calling the follow command several times
_cleos push action eoseosrateio rateproducer '{ "user": "eoseosrateio", "bp": "alohaeostest", "ratings_json": "{\"transparency\":7,\"testnets\":8,\"tooling\":7,\"infra\":6,\"community\":9}"  }'  -p eoseosrateio@active_

**3.** checks the sumatory with the command
_cleos  get table eoseosrateio eoseosrateio stats_

for clean the stats use:
_cleos push action eoseosrateio erase '[]'  -p eoseosrateio@active_

### CODE REVIEW

**Comment by murillojorge** [comment]
@kriskoin please update branch.

**Comment by murillojorge** [comment]
@kriskoin categories must be as follows:
Transparency
Infrastructure
Trustiness
Community
Development

Thanks!

**Comment by kriskoin** [comment]
> @kriskoin please update branch.

Done

**Comment by kriskoin** [comment]
> @kriskoin categories must be as follows:
> Transparency
> Infrastructure
> Trustiness
> Community
> Development
> 
> Thanks!

Done

**Comment by kriskoin** [comment]
doble checked against the jungle net

1. compile adding the full path of the contract using the flag -I

eosio-cpp eoseosrateio.cpp -o eoseosrateio.wasm -abigen -I {CONTRACT_PATH}

2. feed the stats, calling the follow command several times
cleos -u http://monitor.jungletestnet.io:8888 push action eoseosrateio rateproducer '{ "user": "eoseosrateio", "bp": "alohaeostest", "ratings_json": "{"transparency":7,"testnets":8,"tooling":7,"infra":6,"community":9}" }' -p eoseosrateio@active

3. checks the tables with the commands
cleos -u http://monitor.jungletestnet.io:8888 get table eoseosrateio eoseosrateio stats
cleos -u http://monitor.jungletestnet.io:8888 get table eoseosrateio eoseosrateio bps
for clean the stats use:
cleos -u http://monitor.jungletestnet.io:8888 push action eoseosrateio erase '[]' -p eoseosrateio@active

**Comment by murillojorge** [comment]
Approved.

**Comment by xavier506** [comment]
@kriskoin  nos podes explicar por favor como estamos usando la libreria de rapid json en este contrato. Gracias!

**Comment by kriskoin** [comment]
> @kriskoin nos podes explicar por favor como estamos usando la libreria de rapid json en este contrato. Gracias!

el código de la librería se instala en el mismo directorio del contrato contracts/eoseosrateio/rapidjson
para compilarlo  se debe de incluir el flag de compilacion **-I**  full path de la libreria
eosio-cpp eoseosrateio.cpp -o eoseosrateio.wasm -abigen **-I /home/root/eos-rate/contracts/eoseosrateio/rapidjson**

**Comment by kriskoin** [comment]
> @kriskoin nos podes explicar por favor como estamos usando la libreria de rapid json en este contrato. Gracias!

los valores del rating vienen en un json y es necesario procesarlos como valores numéricos
hay que convertir este string 
"{"transparency":7,"Infrastructure":8,"Trustiness":7,"Development":6,"community":9}"
a esta estructura:
TABLE block_producers_stats {
      name bp;
     float Transparency;
     float Infrastructure;
     float Trustiness;
     float Community;
     float Development;
      uint32_t created_at;
      uint32_t updated_at;
      uint64_t primary_key() const { return bp.value; }
    };

**Pull request merged**
